# fly.toml app configuration file generated for dws-site on 2023-09-30T19:34:40+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "dws-site"
primary_region = "ams"

[build]
  image = "ksjusha/dws-site:latest"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
