# Generated by Django 4.2.5 on 2023-09-17 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dws_site', '0002_category_alter_dws_price_alter_dws_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dws',
            old_name='category',
            new_name='cat',
        ),
    ]
