# Generated by Django 4.2.5 on 2023-09-23 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dws_site', '0006_product_delete_dws'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'товар', 'verbose_name_plural': 'товары'},
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(verbose_name='название товара'),
        ),
    ]
