# Generated by Django 4.2.5 on 2023-09-25 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.CharField(null=True, verbose_name='телефон для связи'),
        ),
    ]
