# Generated by Django 4.2.5 on 2023-09-25 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_company_tax_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='post_adress',
            field=models.TextField(verbose_name='почтовый адрес'),
        ),
    ]
