# Generated by Django 4.2.5 on 2023-09-25 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dws_site', '0008_rename_product_id_product_product_art'),
        ('order', '0004_alter_order_post_adress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='dws_site.product', verbose_name='товар'),
        ),
    ]
