# Generated by Django 4.2.5 on 2023-09-26 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_out_reg', '0002_remove_profile_comments'),
        ('order', '0005_alter_orderitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='login_out_reg.profile'),
        ),
    ]
