# Generated by Django 4.2.5 on 2023-09-26 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_out_reg', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='comments',
        ),
    ]
